### ISSUE TITLE
non-hetzner load balancers

### ISSUE THREAD

**Issue by aemadrid-twx** [vitobotta/hetzner-k3s#114]
I'm concerned about cost and would like to create load balancers that do not use Hetzner service but  use Traefik/Nginx/etc. Is that possible? Easy?

**Comment by vitobotta** [comment]
You can use a single load balancer with any ingress controller, and then share that single load balancer with as many ingress resources as you want.

**Comment by orefalo** [comment]
right, but this doesn't solve the cost issue, right?
You still have to pay for a single load balancer...

**Comment by vitobotta** [comment]
The alternative is to install the ingress controller using host ports so that requests go directly to the nodes without a load balancer. In this case you'd just need to enable ports 80 and 443 in the firewall that the tool creates. At the moment you need to make this change manually (it's very easy), but I am gonna add an option to the configuration so it can be automated by the tool.

Personally I don't recommend this approach, because you'd need to keep your DNS records up to date if/when the IPs of the nodes change (for example, say that a node becomes problematic and you want to replace it). With a load balancer you don't need to worry about this because it's handled automatically by Kubernetes.

**Comment by orefalo** [comment]
agreed, but the associated cost is significant if I recall. so for a dev,qa server, it would do.
the firewall can also be done with iptables to further reduce $$$

my current setup uses terraform and k3sup to provision a 3 nodes cluster. will give this project a try when I can free up some time.

**Comment by vitobotta** [comment]
A load balancer is 5.39e + VAT if you are in the EU, and like I said you can share a single load balancer with many ingress resources. Isn't that a small fraction of the cost of an entire cluster? IMO it's the easier option but like I said you can still configure the ingress controller with host ports, so you don't need to create a load balancer in that scenario.

**Comment by vitobotta** [comment]
Closing this since it's not an issue with the tool. For general discussions and questions feel free to start a thread in https://github.com/vitobotta/hetzner-k3s/discussions. Thanks
