### ISSUE TITLE
Public IP in every node not needed

### ISSUE THREAD

**Issue by fmonera** [vitobotta/hetzner-k3s#152]
I don't think having a public IP on every node is needed. Maybe only in CP.

Is there any reason you need a public IP on worker nodes?

**Comment by vitobotta** [comment]
The public IP is needed, otherwise the tool - running on your computer - would not be able to SSH into the nodes and run commands to set up Kubernetes and other components.

**Comment by fmonera** [comment]
In fact you can ssh into any node through one public IP using the ssh option "ProxyJump". 

Let's say that the public IP is attached to node "cp-01", and we want to access "wk-01" and "wk-02". We just need on local machine, a custom ssh config file with this content:

Host cp-01
  Hostname 111.111.111.111
  Port 22
  user root

Host wk-01
  Hostname 10.0.0.3
  User root
  ProxyJump cp-01

Host wk-02
  Hostname 10.0.0.4
  User root
  ProxyJump cp-01

Now you can use (from local machine):

# ssh -F custom_config wk-01
# ssh -F custom_config wk-02

It will work the same way as a direct connection, with everything working as it should (scp, ssh -L or whatever you want to use).

Considering Hetzner is a low cost solution, saving money on unnecessary public IPs might help a lot of people and projects that are low on budget.

Probably, all control plane nodes will still need a public IP, but you can save money without exposing workers.

**Comment by vitobotta** [comment]
I am not sure I would implement this because I don't think it's supported by the Crystal library I use for SSH connections. 
If you want to restrict SSH access to your nodes, you can already specify which IPs or IP ranges are allowed for the connectiuon. This uses the Hetzner firewall, so traffic from disallowed IPs doesn't even reach your nodes. No other ports are exposed to the Internet either, just SSH behind the firewall, so I think it's good enough at the moment.

**Comment by Renegade1912** [comment]
> The public IP is needed, otherwise the tool - running on your computer - would not be able to SSH into the nodes and run commands to set up Kubernetes and other components.

I just created a temp server inside my project to run the scripts. Maybe implement a way to create it like this, in the same private network, to not need a public ip on every worker? This will need to specify the private network in the config i think, since it needs to be present before. 

I mean, public ipv4 is like 60cent, so ...

**Comment by fmonera** [comment]
Yes, IPs are not very expensive. Every other automated cluster deploy tools creates a public IP for each server, so there must be something I don't really understand that makes it a requirement.

When I manually create my clusters, I just need a single IP. Easier to protect and (a bit) cheaper.

Anyway, this is not very important, so I am closing the Issue.

**Comment by CapitanMurloc** [comment]
Although I don't think it is important, from a safety point of view it is. I think it would be good to return to this subject.
