### ISSUE TITLE
Error deploying Hetzner Cloud Controller Manager

### ISSUE THREAD

**Issue by fmonera** [vitobotta/hetzner-k3s#177]
I just launched the script and it fails on the deploying Hetzner Cloud Controller Manager step:

```
Deploying Hetzner Cloud Controller Manager...
error: unable to read URL "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml", server reported 404 Not Found, status code=404
Failed to deploy Cloud Controller Manager:
error: unable to read URL "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml", server reported 404 Not Found, status code=404
```

**Comment by rafalkrupinski** [comment]
That path is hardcoded :/
hetzner-k3s shouldn't use the latest version at all, it should be [configurable](https://github.com/hetznercloud/hcloud-cloud-controller-manager#with-networks-support).

**Comment by vitobotta** [comment]
I have it on my list to make it configurable when I have some time.

**Comment by vitobotta** [comment]
I am finally having time to work on the project this weekend. As for this issue, not sure what happened when you opened it because I am unable to reproduce it. The file can be downloaded and creating clusters works just fine, so perhaps it was something temporary with Github.

I was planning on making the version of the CCM customizable in the configuration but the latest version works fine with all the recent versions of k3s, and even in the version matrix you can see in the page you linked to the manifest for the various versions is the same except for 1.23, but the latest manifest works fine with 1.23. 

So for the time being I am keeping the latest CCM version by default until something changes in the CCM versioning.

**Comment by rafalkrupinski** [comment]
The problem was that the file was absent from the release assets. It would help the next time it happens to be able to configure it, for example with the previous version.
