### ISSUE TITLE
Further Access Restrictions using the firewall

### ISSUE THREAD

**Issue by deveth0** [vitobotta/hetzner-k3s#18]
Hey,
the tool creates a loadbalancer that forwards 6443 to the internal network. 
As far as I understands, this makes the firewall rule that allows access to 6443 obsolete and it should be removed, so it's not possible to access the nodes directly.

Furthermore I think it would be helpful to have an option, to restrict access to SSH to specific IPs (e.g. company network) to further harden the cluster.

**Comment by vitobotta** [comment]
Yeah the reason why the firewall includes that rule is that for single-master, non HA clusters the tool doesn't create the load balancer since it wouldn't be needed, so that rule allows you to connect to the single master for the API server.  I could change it so that it only adds that rule for non HA clusters though. 

As for the SSH think I'll take a look when I have more time. Thanks for the suggestions!

**Comment by vitobotta** [comment]
Hi @deveth0 - in 0.4.0 port 6443 is opened on the nodes only if it's a non HA cluster, without the load balancer. I've also added the ability to specify which networks are allowed to SSH into the nodes. Thanks for the suggestions!

**Comment by deveth0** [comment]
Tested and confirmed!
