### ISSUE TITLE
Enable multi-master HA cluster with kube-vip?

### ISSUE THREAD

**Issue by bluepuma77** [vitobotta/hetzner-k3s#218]
Documentation states

> the setting api_allowed_networks allows specifying which networks can access the Kubernetes API, but this only works with single master clusters currently. Multi-master HA clusters require a load balancer for the API, but load balancers are not yet covered by Hetzner's firewalls

Can't this be solved with [kube-vip](https://kube-vip.io/)?

> kube-vip provides Kubernetes clusters with a virtual IP and load balancer for both the control plane (for building a highly-available cluster) and Kubernetes Services of type LoadBalancer without relying on any external hardware or software.

kube-vip is also mentioned on the official [High Availability Considerations](https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#options-for-software-load-balancing) page.

**Comment by vitobotta** [comment]
I am not familiar with it so I am not sure. But the goal of this project is to make it as easy and quick as possible to get a functional cluster working in Hetzner Cloud, which means using the standard resources including a normal load balancer. Configurations like what you mention are a little out of scope at the moment. I can take a look but not sure when because I have several things planned that I think have priority for the project at this stage.

**Comment by vitobotta** [comment]
Closing because it's out of scope and I am not planning to implement this for the time being. Of course, if you or anyone can create a PR for this I would appreciate.
