### ISSUE TITLE
Volume auto scaling 

### ISSUE THREAD

**Issue by gedw99** [vitobotta/hetzner-k3s#256]
I need to have the volumes auto scale . Does this do that ?

so you never run out of disk, it resized the volume on the fly

**Comment by vitobotta** [comment]
Please don't open a new issue for every question. Continue here https://github.com/vitobotta/hetzner-k3s/discussions/258.

Volumes support expansion but they don't "autoscale". You need to edit the PVC to increase the storage and then restart the deployment so that the pods get rescheduled. This is required for the resizing to happen.
