### ISSUE TITLE
Validating configuration hangs on IPv6

### ISSUE THREAD

**Issue by Tridie2000** [vitobotta/hetzner-k3s#282]
When I add an IPv6 address to the `ssh_allowed_networks` or `api_allowed_networks` blocks, the tool hangs at "Validating configuration..."

```
ssh_allowed_networks:
  - 0.0.0.0/0
  - ::/0

api_allowed_networks:
  - 0.0.0.0/0
  - ::/0
```

hetzner-k3s --version => 1.1.5
macOS => 14.0

**Comment by vitobotta** [comment]
I haven't done any testing with ipv6 unfortunately.

**Comment by vitobotta** [comment]
Hi @Tridie2000 - did you get it working eventually?

**Comment by dperetti** [comment]
Same issue for me.

**Comment by Tridie2000** [comment]
No, I did not get it working with IPv6 addresses.

**Comment by jpetazzo** [comment]
I noticed the same issue (when trying to provision a "pure IPV6" cluster). I'm going to try and investigate further.

**Comment by jpetazzo** [comment]
As I started to debug the issue, I noticed that if I build from source, `hetzner-k3s` doesn't hang anymore at "Validating configuration...", at least on my test configuration,.

I checked by trying exactly the same cluster configuration, on the same machine, with the same SSH keys etc. (to make sure the problem wouldn't come from e.g. an SSH agent, like suggested in #320 ), and with the 1.1.5 release downloaded from GitHub, it hangs at "Validating configuration..." while with the version that I just built from `main`, it doesn't hang.

I suppose there could be two possible issues:
- a bug in the older version of the code, that was fixed since then
- a subtle difference in build environment

For what it's worth, I've built inside the dev container. I'm going to document how to run and build with the build containers if other folks want to try and see if that helps.

**Comment by vitobotta** [comment]
@jpetazzo in main I upgraded the ssh2 shard, so it's very likely that the new version addresses some issues with SSH. Nice to hear that you couldn't reproduce it with main. I will release v2.0.0 as soon as I have finished work in https://github.com/vitobotta/hetzner-k3s/pull/348.

**Comment by vitobotta** [comment]
@jpetazzo rc1 of v2 is now available. Would you be able to help with testing? If yes see https://github.com/vitobotta/hetzner-k3s/discussions/385 for details on the rc1. Thanks

**Comment by jpetazzo** [comment]
Absolutely! I'll give it a try this week and report back. Thank you for all the hard work!

**Comment by vitobotta** [comment]
> Absolutely! I'll give it a try this week and report back. Thank you for all the hard work!

Awesome, thanks!
