### ISSUE TITLE
Is it safe to use the rescale option for the Hetzner Load Balancer?

### ISSUE THREAD

**Issue by alamos-gmbh** [vitobotta/hetzner-k3s#286]
Hello,

I'm pretty sure the answer is yes, but just to be sure:

As the hetzner load balancer is provisioned via this wonderful script, is it still safe to rescale the load balancer to a "bigger one" manually?

![Screenshot 2023-11-17 at 14 53 49](https://github.com/vitobotta/hetzner-k3s/assets/46443521/4a507ea4-6a38-4701-a2e3-6a51634f6ed1)

Sorry for creating this as an issue

**Comment by vitobotta** [comment]
Hi, it depends. If you are referring to the load balancer hetzner-k3s provisions for the Kubernetes API then the answer is yes, you can rescale as long as the name of the load balancer doesn't change. However I am not sure about load balancers provisioned for your apps inside the cluster as I haven't tried. I suspect it might not work because the Hetzner Cloud Controller Manager acts as a reconciliation loop, so it's possible that it will revert to the old type of load balancer once you make changes manually. It's something you need to test. Since there is a little downtime involved in the scaling, I would probably just delete the service and recreate it with the correct annotation for the bigger load balancer.

**Comment by alamos-gmbh** [comment]
Thank you for the quick response.
Actually i was referring to the worker nodes' loadbalancer. 
I followed this tutorial to setup the cluster 
https://github.com/vitobotta/hetzner-k3s/blob/main/wiki/Setting%20up%20a%20cluster.md

It mentions no loadbalancer type, but I found that you referenced this page

https://pkg.go.dev/github.com/hetznercloud/hcloud-cloud-controller-manager/internal/annotation

Here you can find this annotation
`
LBType Name = "[load-balancer.hetzner.cloud/type](http://load-balancer.hetzner.cloud/type)"`

So I guess adding this to the ingress controller annotations (ingress-nginx-annotations.yaml in the wiki / tutorial), specifying the desired type will do the job?

If this is the right way to do it, I can test and add it to the docs

**Comment by vitobotta** [comment]
Sorry I had misunderstood. Yes just specify the type with the annotation, LB11/LB21/LB31 I think are the types. Also I tried starting with LB11 and then changing the annotation to use LB31, and the load balancer was upgraded without changing IP address :)

**Comment by vitobotta** [comment]
@alamos-gmbh I guess we can close this by now?

**Comment by alamos-gmbh** [comment]
Hi, sorry I did not see the notification.
Yes, this can be closed, although not yet tested, but the docs are clear.

As we like this project a lot:
What do you think about creating a community around it, like a discussion board, google group etc?
So people can discuss without labeling everything as "issue".
We could help with that

**Comment by vitobotta** [comment]
@alamos-gmbh like https://github.com/vitobotta/hetzner-k3s/discussions? :)
