### ISSUE TITLE
Possibility to rescale `masters_pool` `instance_type`

### ISSUE THREAD

**Issue by aaronschweig** [vitobotta/hetzner-k3s#287]
Hello 👋 

First of all thanks for providing this tool - I used it for multiple clusters and it always worked like a charm!

I would have one question though: Is there a possibility to change the `instance_type` for the `masters_pool`? I could image it possible from a kuberntes POV as I have a HA setup, which would make it possible to recreate the masters one by one with a different machine size.

I do see that the instance type is part of the server name and probably needed in multiple other places. This is why I thought I might ask the creator who probably knows if something like that is possible or not 😄 

Thanks already!

**Comment by vitobotta** [comment]
Hi, at the moment there is a problem with automating the rescaling of instances due to the instance type being part of the instance name. Unfortunately I didn't think about rescaling when I choose the original naming scheme. I need to think about a workaround to automate rescaling for existing cluster.

But you can rescale instances manually and everything will still work as long as you don't change the names of the instances manually.

**Comment by vitobotta** [comment]
Hi @aaronschweig it's been a while but I finally have a week off from work this coming week so I can dedicate some time to the project again. FYI I am planning to exclude the instance type from the naming convention for the servers moving forward, and introduce a setting to opt in to the legacy naming convention for existing clusters. https://github.com/users/vitobotta/projects/4/views/1?pane=issue&itemId=59552602

**Comment by vitobotta** [comment]
FYI the change I mentioned in my last comment is in v2, which should be released probably next weekend, so I am closing this.
