### ISSUE TITLE
Receiving emails from Hetzner when a new node is created with autoscaling

### ISSUE THREAD

**Issue by emrys90** [vitobotta/hetzner-k3s#295]
Hi,

I'm working on migrating my production servers over from Digital Ocean to Hetzner, and trying out your tool.

I seem to be receiving an email though whenever a new node is created using autoscaling, which for my use case can be quite frequent. It says I receive these emails to provide a password for the newly created nodes, because those nodes are not being assigned an SSH key on creation.

This only happens for autoscaling node pools, static size does not send these emails.

**Comment by vitobotta** [comment]
Hi, for the autoscaled nodes to have the SSH key, there should be an SSH key with the same name as the cluster in the Hetzner project; hetzner-k3s creates this key automatically when you run the create command, but skips that if there is already a key with the same fingerprint in the project, because there can't be two identical keys. So if you added your key to the project manually, just delete it and run the create command. The key will be created with the expected name and will be added to the autoscaled nodes as well. In the future I might make it possible to specify an existing key in the config file.

**Comment by emrys90** [comment]
Thanks for the quick reply! What should I do in the case that I need 2 clusters? Should I be doing 1 cluster per project instead?

**Comment by emrys90** [comment]
Great, thank you!

**Comment by vitobotta** [comment]
You're welcome :)
