### ISSUE TITLE
Use of dedicated servers

### ISSUE THREAD

**Issue by stefandevo** [vitobotta/hetzner-k3s#34]
Hi,
Any plans or guidance to setup k3s on dedicated servers? I know you are running dynablogger on dedicated servers now 😀

**Comment by vitobotta** [comment]
Hi, actually I migrated back to cloud servers in the new US location. The reason is that it's easier and quicker to scale and manage K8s with this tool, which I couldn't use with dedis. Installing k3s on its own on dedis is pretty simple IMO. What are you looking to automate? There's also another tool called k3sup (https://github.com/alexellis/k3sup) that makes it a bit simpler. The purpose of my tool is to speed up creating all the resources, not just install K8s. But if you already have some servers up and running maybe you can use k3sup. :)

**Comment by stefandevo** [comment]
Ah ok; I was just curious how you dealt with private networks, cloud controller etc, not specifically installing k3s. But if you moved back to cloud, no problem!
