### ISSUE TITLE
no public IP for API loadbalancer 

### ISSUE THREAD

**Issue by jampy** [vitobotta/hetzner-k3s#369]
I would like to restrict k8s API access to a Hetzner private network.

Using `existing_network` I can configure `hetzner-k3s` to attach all nodes to a pre-existing private network, fine.

Questions:

- is there an option to have `hetzner-k3s` automatically attach the **API** load balancer (created by hetzner-k3s) to the same network?
- is there an option to disable the **public** interface on the **API** load balancer, so that it is reachable via the private network only

or, alternatively:

- can I pre-configure a Hetzner load balancer (just as described above) and have `hetzner-k3s` reuse it, similarily to `existing_network`?

**Comment by vitobotta** [comment]
Sorry about the delay, either I didn't receive notifications about this or I missed them. 

The tool already attaches the API load balancer to the private network and uses the private IP for the connection when a private network is in use, but it currently always activates the public interface. Making it possible to disable the public interface for the load balancer is a trivial change though so I am planning to do it in 2.0.1.

**Comment by vitobotta** [comment]
HI, I just released v2.0.0 and since several people had asked about removing the requirement for a load balancer, I also implemented this. The new version no longer creates a load balancer for the API; instead, it generates a kubeconfig file with multiple contexts so you can switch from a master to another if needed. This saves on cost and is also more secure since the access to the API on the nodes directly can be restricted by IP address in the configuration file, using the firewall (while load balancers don't support the firewalls yet).

Since the load balancer for the API is no longer a thing I am closing this issue, but feel free to open another one if you have problems with the new approach.
