### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by quorak** [vitobotta/hetzner-k3s#46]
Awesome project and it worked out of the box.
Do you plan to add encryption options, like:

- [ ] traffic encryption with wireguard https://github.com/rancher/docs/blob/master/content/k3s/latest/en/installation/network-options/_index.md#flannel-options
- [ ] encryption at rest with tang https://community.hetzner.com/tutorials/install-encrypted-ubuntu-2004-with-automated-unlock-via-tang-and-clevis

This would help to make it a great choice! Happy to help with it!

**Comment by vitobotta** [comment]
Hi, I haven't enabled traffic encryption yet since by the default clusters created with this tool use the private network and encryption worsen performance. But I can add an option to enable either wireguard or ipsec since both are supported by k3s. I will take a look when I have a little more time.

I'm not familiar with tang but generally speaking you could create a ready snapshot with the configuration you wish, and use that as the image used for creating the cluster. There's an option that you can set in the config file.

**Comment by vitobotta** [comment]
0.5.0 adds an option to enable encryption with ipsec, which is natively supported by k3s without requiring any additional packages or kernel modules. I'm closing this but feel free to reopen if you have problems with it or have more suggestions.
