### ISSUE TITLE
Issue with placement groups

### ISSUE THREAD

**Issue by krisnod** [vitobotta/hetzner-k3s#60]
I tried to upgrade my cluster to have more than 10 nodes which seems not to be possible because all nodes created by this solution is added to single placement group and Hetzner only allows 10 server to single group.

As a workaround I do a little bit rearranging of my nodes using Hetzner's cloud console, but I think that's not a most intuitive solution because it also requires shutdown those servers which you want to move to another placement group. 

One solution could be that somehow we are able to define separated placement groups for different node pools (master and worker pools).

**Comment by vitobotta** [comment]
Hi, thanks for pointing out about the 10 servers per group limit! I wasn't aware of it as I have only created small clusters so far. I will add support for creating one group per pool as you suggested. Perhaps tomorrow if I can.

**Comment by vitobotta** [comment]
Done in v0.5.1. Now each node pool gets its own placement group and I have added a validation that limits each pool to max 10 nodes. Existing clusters won't be affected by this change unless you replace a node pool, in which case the new node pool gets a separate placement group. I'm closing this for now since it's done but please reopen if you find any issues with this change. :)
