### ISSUE TITLE
Idea: Multi-Location Cluster

### ISSUE THREAD

**Issue by matthiasbruns** [vitobotta/hetzner-k3s#66]
Since you already support a HA setup, would it be possible to have location groups?
Spanning nodes and workers over several locations would help if one location burned down :D

**Comment by vitobotta** [comment]
Interesting idea. It should be possible I think because if I remember correctly the private networks work across locations. I've added a card for this at https://github.com/vitobotta/hetzner-k3s/projects/1#card-77987216

It wouldn't be a good idea to spread the masters across locations because etcd is latency sensitive. But it Thanks for the suggestion!

**Comment by vitobotta** [comment]
Hi, I've released v0.5.4 that allows you to specify a different location for each node pool, provided that all node pools (workers and masters) are in the same network zone. Currently, means that either all the nodes are located in Ashburn, or none of them, since the Ashburn location is in a different network zone from that of the other locations. Can you please try a multi-zone cluster and let me know if you run into any issues? Thanks.

**Comment by vitobotta** [comment]
Forgot to mention, the masters must all be in the same location because etcd is latency sensitive.

**Comment by matthiasbruns** [comment]
Sorry totally lost track of time :(

**Comment by vitobotta** [comment]
Np, can I close this now?
