### ISSUE TITLE
I followed the tutorial but get "Bad Request" when "uses-proxyprotocol" is set

### ISSUE THREAD

**Issue by jr-dimedis** [vitobotta/hetzner-k3s#87]
I am pretty sure this is no issue with hetzner-k3s itself and most probably my fault (I am a Kubernetes beginner), but maybe this is a no brainer for you so I decided to open an issue for this. Just tell me if that's not the right place (and I would be very thankful if you could point me to the right place then ;)).

I just followed the tutorial in the Wiki and created a small test cluster with one master and one worker node. At first everything worked like a charm as described.

But when I accessed the hello-world app (no matter if I use the proper connected DNS name or plain IP or nip.io address) I got a 400 response without further information.

I suspected the "uses-proxyprotocol" setting to be the cause of this and disabled it in the Hetzner Cloud Console. And voila: the hello-world app worked. Of course I like to you use the setting for the reasons you mentioned in the docs.

Do you have any idea what could be the cause for this? If you need any further information please ask and I will give it to you.

Thanks!

**Comment by vitobotta** [comment]
Hi, yes the misconfiguration of the proxy protocol will indeed lead to 400s. To prevent that you need to ensure that it is enabled both for the load balancer service and in the nginx config map. See the Wiki page at the paragraph starting with

```
19. load-balancer.hetzner.cloud/uses-proxyprotocol: "true" annotation requires use-proxy-protocol: "true" for ingress-nginx, so let's create file: touch ingress-nginx-configmap.yaml 20. Add content to just created file: nano ingress-nginx-configmap.yaml
```

Once you apply that config map it will reload Nginx with that config change and everything should work just fine with the proxy protocol enabled.

Also, keep in mind that due to the reconciliation loop in Kubernetes by the CCM, any change you make directly to the load balancer in the Hetzner control panel will be automatically reverted at some point to reflect the config stored in Kubernetes as the desired state.

**Comment by jr-dimedis** [comment]
Hi Vito, thanks for your quick reply! Yes, it works now! :)

I stopped the tutorial at this point, because I thought "one step after another" and since paragraph 19 is introduced with "If you need LetsEncrypt" I thought everything should work using plain HTTP up to this point. Of course, on closer inspection of the config map, I now see that, strictly speaking, it has nothing to do with it and just is the counterpart of the load balancer proxy configuration.

Thanks again for your great work and your support.
